name: Build, upload & deploy

on:
  push:
    branches:
      - 'main'
      - 'develop'
  schedule:
    - cron: "0 6 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get version tag
        run: echo RELEASE=$(git tag) >> $GITHUB_ENV
      - name: Build and push main
        uses: docker/build-push-action@v4
        if: github.ref == 'refs/heads/main'
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: netwatching/netregator:latest, netwatching/netregator:${{ env.RELEASE }}
      - name: Build and push other
        uses: docker/build-push-action@v4
        if: github.ref != 'refs/heads/main'
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: netwatching/netregator:${{ github.head_ref || github.ref_name }}, netwatching/netregator:${{ env.RELEASE }}-${{ github.head_ref || github.ref_name }}
#  deploy:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - name: trigger deploy
#        run: | 
#          curl -X POST ${{ secrets.PORTAINER_WEBHOOK_URL }} \
#           -A "Mozilla/5.0 (compatible;  MSIE 7.01; Windows NT 5.0)" \
#           -H "CF-Access-Client-Id: ${{ secrets.CLOUDFLARE_CLIENT_ID }}" \
#           -H "CF-Access-Client-Secret: ${{ secrets.CLOUDFLARE_CLIENT_SECRET }}" \
#           -H "SKIP_CLOUDFLARE_CHECKS: ${{ secrets.CLOUDFLARE_SKIP_BOTS }}" \
#           -L
